### ISSUE TITLE
Unknown storage engine 'columnstore'

### ISSUE THREAD

**Issue by Labib123** [mariadb-corporation/dev-example-flights#1]
I installed all the required packages for client and api as well as MariaDB, but I get this error "Unknown storage engine 'columnstore'" when I run the "./create_and_load.sh" file. Any suggestion?  

Operating System: Windows 10

**Comment by rhedgpeth** [comment]
@Labib123 Apologies for not seeing this much, much sooner! For some reason I didn't get a notification for this. 

The problem you're likely running into is that you need to install the ColumnStore engine. This is something I will add more clarification on in the README. 

Docs on installation -> https://mariadb.com/kb/en/installing-and-configuring-mariadb-columnstore/

However, the quickest way to test out ColumnStore is to use the ColumnStore Docker image. The container you'll spin up from the image will already come with ColumnStore installed -> https://hub.docker.com/r/mariadb/columnstore/
